### ISSUE TITLE
ValueError: Points cannot contain NaN

### ISSUE THREAD

**Issue by jpsml** [lvsn/6DOF_tracking_evaluation#5]
I am trying to train using the generate_dataset.sh script and the clock model from the dataset sample, but I am getting the following output: 

Generating training data...
Compute Mean bounding box
Traceback (most recent call last):
  File "dataset_generator.py", line 100, in <module>
    object_max_width = maximum_width(model_3d) * 1000
  File "/home/jpsml/6DOF_tracking_evaluation/ulaval_6dof_object_tracking/utils/pointcloud.py", line 6, in maximum_width
    hull = ConvexHull(points)
  File "qhull.pyx", line 2359, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 279, in scipy.spatial.qhull._Qhull.__init__
ValueError: Points cannot contain NaN
Generating validation data..
Compute Mean bounding box
Traceback (most recent call last):
  File "dataset_generator.py", line 100, in <module>
    object_max_width = maximum_width(model_3d) * 1000
  File "/home/jpsml/6DOF_tracking_evaluation/ulaval_6dof_object_tracking/utils/pointcloud.py", line 6, in maximum_width
    hull = ConvexHull(points)
  File "qhull.pyx", line 2359, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 279, in scipy.spatial.qhull._Qhull.__init__
ValueError: Points cannot contain NaN

**Comment by MathGaron** [comment]
Hey,
I think it might be a bug with the version of numpy/scipy. Can you tell me what are your versions?

**Comment by jpsml** [comment]
numpy-1.16.2
scipy-1.2.1

**Comment by MathGaron** [comment]
Ok so on my setup I have numpy 1.13.3 and I am quite sure that this is the bug.

Else you might need to chase that Nan (probably happening during the loading of the .ply). If you do, do not hesitate to write your fixes here or do a pull request! I might dig into that later though.. I am currently quite busy.

**Comment by jpsml** [comment]
Yes, it worked with numpy 1.13.3. Thank you very much!
